project/news/urls.py
from django.urls import path

from .views import NewsApi, NewsView

app_name = "news"

urlpatterns = [
    path("", NewsView.as_view(), name="list"),
    path("json/", NewsApi.as_view({"get": "list"}), name="json"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news')),
]

project/news/models.py
from django.db import models


class Source(models.Model):
    '''
    Using column named id in Django requires values to be unique, use name source_id instead
    '''
    source_id = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255)

    class Meta:
        unique_together = ("source_id", "name")


class News(models.Model):
    """
    According to newsapi examples, fields which could be null marked as null in the model
    """

    source = models.ForeignKey(Source,on_delete=models.CASCADE)
    author = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(null=True, blank=True)
    published_at = models.DateTimeField()
    url = models.URLField(max_length=500,unique=True)
    url_to_image = models.URLField(max_length=500,null=True, blank=True)

    class Meta:
        ordering = ["-published_at"]

project/news/forms.py
from django import forms

from .mixins import UnderscoreizeFormDataMixin
from .models import News


class NewsForm(UnderscoreizeFormDataMixin, forms.ModelForm):

    published_at = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M:%SZ"])

    class Meta:
        model = News
        fields = [
            "author",
            "title",
            "description",
            "content",
            "published_at",
            "url",
            "url_to_image",
        ]

project/news/views.py
from django.views.generic import ListView
from rest_framework.renderers import JSONRenderer
from rest_framework.mixins import ListModelMixin
from rest_framework.viewsets import GenericViewSet

from .models import News
from .serializers import NewsSerializer


class NewsView(ListView):
    queryset = News.objects.all()[:20]


class NewsApi(ListModelMixin, GenericViewSet):
    queryset = News.objects.all()[:100]
    serializer_class = NewsSerializer

project/news/templates/news/news_list.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Latest News!</title>
</head>
<body>
<div class="container">
    <div class="row mb-3">
        <div class="col-12">
            <h1>Latest News</h1>
            <a href="{% url 'news:json' %}" class="btn btn-primary mt-3">JSON</a>
        </div>
    </div>

    {% for news in object_list %}
        <div class="row mb-3">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ forloop.counter }}. {{ news.title }}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">{{ news.published_at }}</h6>
                        <p class="card-text">{{ news.description }}</p>
                        <a href="{{ news.url }}" class="card-link">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>